### PR TITLE
Correct regex

### PR DESCRIPTION
**Pull request by kellen**
Correct regex from  http://www.i-programmer.info/images/stories/News/2014/Dec/B/grid.pdf

### CODE REVIEW

**Comment by Jimbly** [comment]
Good catch!  Now I wonder if I solved the wrong crossword puzzle when I did this years ago... =)

**Comment by kellen** [comment]
Your transposed regex still matches the solution, so no worries :)

**Comment by Jimbly** [comment]
Purely out of curiosity, how did you possibly notice this? =)

**Comment by Jimbly** [comment]
So, a user is reporting, in #5, that this fix actually makes the puzzle unsolveable.  And, actually, looking at it closer, it appears it was correct before your PR (*all* of those clues are "transposed" compared to the print one, because they're literally upside down - the print one they are applied lower-right to upper-left, in mine they are applied upper-left to lower-right).

**Comment by kellen** [comment]
Oooooh, that actually make sense, now that I'm looking at the original display vs your display. I've got the same solution as given in #5, but I didn't test the change first, sorry!

**Comment by Jimbly** [comment]
No worries!  Your PR did, however, cause me to notice that I had an unreviewed pull request from close to a couple years ago, (which GitHub probably never emailed me about due to settings at the time...), so you can at least feel satisfied that you generally increased the good in the world ;).  Unless you look at it from the perspective of my current boss, as I'm now wasting time solving this puzzle again... =)

**Pull request merged**
