### PR TITLE
Add Digital by Emi

### PR DESCRIPTION
**Pull request by emilyploszaj**
Hi! I've been a big fan of this site for a while and saw that a new puzzle was added recently, so I tried my hand at setting.

There is one valid solution for Digital:
```
      # A 1 B C 8 6
     A Y A N B B B I
    A A A O N T O O T
   F F F F F 1 B O B B
  I F F F C N O I C P S
 F O F O F K B O B B K 6
I C 1 I F H E L S E C 8 I
 F P F P O B Y F P T X Y
  M P P P P M B B S Y Y
   O C C E M M O T 1 Y
    U C B J A V A C Y
     S P P P R S R D
      E P E P A C D
```

### CODE REVIEW

**Comment by Jimbly** [comment]
Cool, thanks!  Pushed live to http://jimbly.github.io/regex-crossword/  I'll have to give it a try later =)

**Comment by Jimbly** [comment]
Hi @emilyploszaj!

Neat puzzle.  I played through, and one hex has 5 value answers, allowing for 5 unique solutions.

Screenshot 2023-05-14 200749

Can use any of `FK_BM` in that open hex (the `F*H*` in the bottom right do nothing since neither F nor H are in PARTITION anyway.  Maybe `A*F+H+` would do the trick and not make anything else much easier?)

**Comment by emilyploszaj** [comment]
Oh right you are, yeah I think switching it to A*F+H+ is the right call then, maybe A+F+H+ for the pattern? though that would reveal a character with slightly less logic

**Comment by emilyploszaj** [comment]
Actually, `A*F*H+[^PARTITION]` would work, right? I think that pattern is still aesthetically pleasing

**Comment by Jimbly** [comment]
Yeah, I think that'd work too, sounds good!

**Pull request merged**
